# Site settings
title: Elias Esmaeilzadeh
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
user.name: "Elias Esmaeilzadeh"
user_description: I'm a student of Biology at FUM university & a beginner Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. These days I try to learn more about Software Engineering and improve my abilities. you can contact me via links below my name.
user_title: Contact Me
user.email: "EliasEsmaeilzadeh@gmail.com"
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

baseurl: "EliasEsmaeilzadeh"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
